# Generated by Django 4.2.2 on 2023-06-19 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_image',
            field=models.ImageField(blank=True, max_length=254, null=True, upload_to='items'),
        ),
    ]
